version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    container_name: karakeep
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3002:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OLLAMA_BASE_URL: http://192.168.86.10:11434
      OLLAMA_KEEP_ALIVE: 5m
      INFERENCE_TEXT_MODEL: gemma3:1b
      INFERENCE_IMAGE_MODEL: gemma3:1b
      INFERENCE_CONTEXT_LENGTH: 1024
      INFERENCE_LANG: english
      INFERENCE_JOB_TIMEOUT_SEC: 60
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: karakeep-meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
