version: "3"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Detroit
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
    networks:
      - arr_network

  watchlistarr:
    image: nylonee/watchlistarr
    container_name: watchlistarr
    environment:
      - RADARR_API_KEY=REDACTED
      - SONARR_API_KEY=REDACTED
      - PLEX_TOKEN=REDACTED
      - RADARR_BASE_URL=http://192.168.86.11:7878
      - SONARR_BASE_URL=http://192.168.86.11:8989
    volumes:
      - ./watchlistarr:/app/config
    restart: unless-stopped
    networks:
      - arr_network

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000  # Set to your user ID
      - PGID=1000  # Set to your group ID
      - TZ=America/Detroit  # Set your timezone
    volumes:
      - ./overseerr/config:/config  # Replace with your config path
    ports:
      - 5055:5055  # Web UI port
    restart: unless-stopped
    networks:
      - arr_network

  prowlarr:
    image: linuxserver/prowlarr:latest  # Or replace with an alternative image
    container_name: prowlarr
    environment:
      - PUID=1000  # Replace with your user ID
      - PGID=1000  # Replace with your group ID
      - TZ=America/Detroit  # Set your timezone
    volumes:
      - ./prowlarr/config:/config  # Replace with your config directory
    ports:
      - 9696:9696  # Web UI port
    restart: unless-stopped
    networks:
      - arr_network

  sonarr:
    image: linuxserver/sonarr:latest  # Or replace with an alternative image
    container_name: sonarr
    environment:
      - PUID=1000  # Replace with your user ID
      - PGID=1000  # Replace with your group ID
      - TZ=America/Detroit  # Set your timezone
    volumes:
      - ./sonarr/config:/config  # Replace with your config directory
      - /mnt/shows:/tv  # Replace with your TV directory
      - /mnt/nas/Transmission/Downloads:/downloads  # Replace with your downloads directory
    ports:
      - 8989:8989  # Web UI port
    restart: unless-stopped
    networks:
      - arr_network

  radarr:
    image: linuxserver/radarr:latest  # Or replace with an alternative image
    container_name: radarr
    environment:
      - PUID=1000  # Replace with your user ID
      - PGID=1000  # Replace with your group ID
      - TZ=America/Detroit  # Set your timezone
    volumes:
      - ./radarr/config:/config  # Replace with your config directory
      - /mnt/movies:/movies  # Replace with your movies directory
      - /mnt/nas/Transmission/Downloads:/downloads  # Replace with your downloads directory
    ports:
      - 7878:7878  # Web UI port
    restart: unless-stopped
    networks:
      - arr_network

  bazarr:
    image: linuxserver/bazarr:latest  # Or replace with an alternative image
    container_name: bazarr
    environment:
      - PUID=1000  # Replace with your user ID
      - PGID=1000  # Replace with your group ID
      - TZ=America/Detroit  # Set your timezone
    volumes:
      - ./bazarr/config:/config  # Replace with your config directory
      - /mnt/shows:/tv  # Replace with your TV shows directory
      - /mnt/movies:/movies  # Replace with your movies directory
    ports:
      - 6767:6767  # Web UI port
    restart: unless-stopped
    networks:
      - arr_network


networks:
  arr_network:
    driver: bridge
