services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true           # Automatically remove old images
      - WATCHTOWER_POLL_INTERVAL=86400    # Check for updates every 24 hours
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Required for container management
    restart: unless-stopped
